# permissions for end users to edit databasehosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databasehost-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: external-database-operator
    app.kubernetes.io/part-of: external-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: databasehost-editor-role
rules:
  - apiGroups:
      - k8s.tuunit.com
    resources:
      - databasehosts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.tuunit.com
    resources:
      - databasehosts/status
    verbs:
      - get
