# permissions for end users to view databaseusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databaseuser-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: database-management-operator
    app.kubernetes.io/part-of: database-management-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseuser-viewer-role
rules:
- apiGroups:
  - k8s.tuunit.com
  resources:
  - databaseusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.tuunit.com
  resources:
  - databaseusers/status
  verbs:
  - get
