# permissions for end users to view databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: database-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: external-database-operator
    app.kubernetes.io/part-of: external-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-viewer-role
rules:
  - apiGroups:
      - k8s.tuunit.com
    resources:
      - databases
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - k8s.tuunit.com
    resources:
      - databases/status
    verbs:
      - get
